# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company <alexander.gilin@sap.com>
#
# SPDX-License-Identifier: CC0-1.0

require: 
  - 'ts-node/register/transpile-only'
  - 'source-map-support/register'
recursive: 
  - 'tests/**/*.spec.ts'
timeout: 80000
